// Cross-language conformance: the Node binding must reach the same accept/reject
// decision as the Rust core for every golden vector in ../../conformance/vectors.json
// (generated by `cargo run -p agentcreds-core --example gen_conformance_vectors`).
// This proves the wire formats (CBOR token/presentation/challenge, JSON credential /
// status list) and the verification logic agree across the language boundary.
//
// Run: node --test test/   (or `npm run test:conformance`)

const { test } = require("node:test");
const assert = require("node:assert");
const { readFileSync } = require("node:fs");
const { join } = require("node:path");

const ac = require("../index.js");

const vectorsPath = join(__dirname, "..", "..", "conformance", "vectors.json");
const suite = JSON.parse(readFileSync(vectorsPath, "utf8"));

const buf = (hex) => Buffer.from(hex, "hex");

// Evaluate AS OF the instant the vectors were generated, not the wall clock.
// Credentials here are century-long, but TOKENS are bounded by the autonomy ladder
// (one hour at L0) - so wall-clock verification would start failing an hour after the
// file was regenerated. `evaluated_at` makes the golden file time-stable without the
// generator having to mint tokens that outlive what the ladder permits.
const EVAL_AT = suite.evaluated_at;
if (typeof EVAL_AT !== "number") {
  throw new Error("vectors.json is missing `evaluated_at` - regenerate it (format >= 3)");
}

// Binding verify methods throw on failure; assert the throw/no-throw matches `expect`.
function checkOutcome(name, expect, verifyFn) {
  if (expect === "accept") {
    assert.doesNotThrow(verifyFn, `${name}: expected ACCEPT but verification threw`);
  } else {
    assert.throws(verifyFn, `${name}: expected REJECT but verification passed`);
  }
}

assert.strictEqual(suite.format, 3, "unexpected vector format version");

// Fixed evaluation instant - the vectors use century-long validity, so any "now" inside
// that window gives the same decision, and pinning it keeps runs reproducible.
const NOW = Math.floor(Date.now() / 1000);

for (const c of suite.cases) {
  test(`conformance: ${c.name} (${c.kind})`, () => {
    const anchor = ac.TrustAnchor.fromDidKey(c.anchor_did);

    switch (c.kind) {
      case "presentation": {
        const pres = ac.Presentation.fromCbor(buf(c.presentation_cbor_hex));
        const challenge = ac.PopChallenge.fromCbor(buf(c.challenge_cbor_hex));
        const action = new ac.Action(c.action.tool, c.action.parameters);
        checkOutcome(c.name, c.expect, () =>
          pres.verifyAt(action, anchor, challenge, c.max_age_secs, EVAL_AT),
        );
        break;
      }
      case "credential": {
        const vc = ac.CapabilityCredential.fromJson(c.credential_json);
        checkOutcome(c.name, c.expect, () => vc.verify(anchor));
        break;
      }
      case "token": {
        const vc = ac.CapabilityCredential.fromJson(c.credential_json);
        const token = ac.DelegationToken.fromCbor(buf(c.token_cbor_hex));
        const action = new ac.Action(c.action.tool, c.action.parameters);
        checkOutcome(c.name, c.expect, () => token.verifyRootedAt(action, vc, anchor, EVAL_AT));
        break;
      }
      // Shape, not just accept/reject: an attenuated chain must be readable THROUGH the
      // binding - depth and the ordered hop DIDs. The accept/reject cases prove the
      // token verifies; this proves the FFI surfaces what it verified.
      case "token_chain": {
        const token = ac.DelegationToken.fromCbor(buf(c.token_cbor_hex));
        assert.strictEqual(
          token.depth(),
          c.expect_depth,
          `${c.name}: depth mismatch across the binding`,
        );
        const dids = token.chain().entries.map((e) => e.agentDid);
        assert.deepStrictEqual(
          dids,
          c.expect_chain_agent_dids,
          `${c.name}: chain agent DIDs differ from the Rust core`,
        );
        break;
      }
      // The relying party's rotation check, in the order the shipping resolver uses it:
      // authorizeIssuer verifies the sealed chain against the PINNED ROOT and refuses a
      // repudiated key, returning the anchor to verify the credential with. `anchor_did`
      // here is the root, not the issuer - a rotated org's issuer DID is not known to
      // the relying party in advance, which is the whole point of pinning the root.
      case "key_history": {
        const history = ac.KeyHistory.fromJson(c.key_history_json);
        const vc = ac.CapabilityCredential.fromJson(c.credential_json);
        checkOutcome(c.name, c.expect, () =>
          vc.verify(history.authorizeIssuer(c.anchor_did, vc.issuer)),
        );
        break;
      }
      // Hybrid R10. The directory is the ONLY thing binding a key to a human, so
      // verifying the signature without consulting it passes the accept case and fails
      // every reject case.
      case "approval_key": {
        const directory = ac.ApproverDirectory.fromJson(c.directory_json);
        const ev = ac.ApprovalEvidence.fromJson(c.evidence_json);
        const action = new ac.Action(c.action.tool, c.action.parameters);
        checkOutcome(c.name, c.expect, () =>
          ev.verifyWithDirectory(action, directory, anchor, NOW, null),
        );
        break;
      }
      // R2 through a trust framework. `anchor_did` is the FRAMEWORK anchor, not the
      // credential's issuer - resolution is the whole point of the case.
      case "trust_config": {
        const vc = ac.CapabilityCredential.fromJson(c.credential_json);
        checkOutcome(c.name, c.expect, () => {
          const config = ac.SignedTrustConfig.fromJson(c.config_json);
          config.verifyCurrent(anchor);
          const registry = ac.TrustRegistry.fromConfig(config, anchor);
          const entry = registry.verifyCredential(vc);
          vc.verify(ac.TrustAnchor.fromDidKey(entry.did));
        });
        break;
      }
      case "revocation": {
        const list = ac.RevocationList.fromJson(c.list_json);
        // The signed list must be authentic against the issuer anchor.
        assert.doesNotThrow(() => list.verify(anchor), `${c.name}: list did not verify`);
        assert.strictEqual(
          list.isRevoked(c.revoked_index),
          true,
          `${c.name}: index ${c.revoked_index} should read as revoked`,
        );
        assert.strictEqual(
          list.isRevoked(c.clear_index),
          false,
          `${c.name}: index ${c.clear_index} should read as not revoked`,
        );
        break;
      }
      default:
        throw new Error(`unknown vector kind: ${c.kind}`);
    }
  });
}
