"""Cross-language conformance: the Python binding must reach the same accept/reject
decision as the Rust core for every golden vector in ../../conformance/vectors.json
(generated by `cargo run -p agentcreds-core --example gen_conformance_vectors`).

Proves the wire formats (CBOR token/presentation/challenge, JSON credential / status
list) and verification logic agree across the language boundary.

Run:  python tests/test_conformance.py     (or `pytest tests/test_conformance.py`)
"""

import json
import sys
import time
from pathlib import Path

import agentcreds as ac

VECTORS = Path(__file__).resolve().parents[2] / "conformance" / "vectors.json"


def _check(name, expect, verify_fn):
    """Binding verify methods raise on failure; assert that matches ``expect``."""
    try:
        verify_fn()
        accepted = True
    except Exception:
        accepted = False
    if expect == "accept" and not accepted:
        raise AssertionError(f"{name}: expected ACCEPT but verification raised")
    if expect == "reject" and accepted:
        raise AssertionError(f"{name}: expected REJECT but verification passed")


#: Evaluation instant, read from the vectors themselves.
#:
#: Credentials in the golden file are century-long, but TOKENS are bounded by the
#: autonomy ladder (one hour at L0), so verifying against the wall clock would start
#: failing an hour after the file was regenerated. Judging as of `evaluated_at` keeps the
#: golden file time-stable without minting tokens that outlive what the ladder permits.
_NOW = int(time.time())


def test_conformance():
    suite = json.loads(VECTORS.read_text())
    _eval_at = suite.get("evaluated_at")
    assert isinstance(_eval_at, int), (
        "vectors.json is missing `evaluated_at` - regenerate it (format >= 3)"
    )
    assert suite["format"] == 3, "unexpected vector format version"

    for c in suite["cases"]:
        anchor = ac.TrustAnchor.from_did_key(c["anchor_did"])
        kind = c["kind"]

        if kind == "presentation":
            pres = ac.Presentation.from_cbor(bytes.fromhex(c["presentation_cbor_hex"]))
            challenge = ac.PopChallenge.from_cbor(bytes.fromhex(c["challenge_cbor_hex"]))
            action = ac.Action(c["action"]["tool"], c["action"]["parameters"])
            _check(c["name"], c["expect"],
                   lambda: pres.verify_at(action, anchor, challenge, c["max_age_secs"], _eval_at))

        elif kind == "credential":
            vc = ac.CapabilityCredential.from_json(c["credential_json"])
            _check(c["name"], c["expect"], lambda: vc.verify(anchor))

        elif kind == "token":
            vc = ac.CapabilityCredential.from_json(c["credential_json"])
            token = ac.DelegationToken.from_cbor(bytes.fromhex(c["token_cbor_hex"]))
            action = ac.Action(c["action"]["tool"], c["action"]["parameters"])
            _check(c["name"], c["expect"],
                   lambda: token.verify_rooted_at(action, vc, anchor, _eval_at))

        elif kind == "token_chain":
            # Shape, not just accept/reject: an attenuated chain must be readable
            # THROUGH the binding - depth and the ordered hop DIDs. The accept/reject
            # cases prove the token verifies; this proves the FFI surfaces what it
            # verified.
            token = ac.DelegationToken.from_cbor(bytes.fromhex(c["token_cbor_hex"]))
            assert token.depth() == c["expect_depth"],                 f"{c['name']}: depth mismatch across the binding"
            dids = [e.agent_did for e in token.chain().entries]
            assert dids == c["expect_chain_agent_dids"],                 f"{c['name']}: chain agent DIDs differ from the Rust core"

        elif kind == "key_history":
            # The relying party's rotation check, in the order the shipping resolver
            # uses it: authorize_issuer verifies the sealed chain against the PINNED
            # ROOT and refuses a repudiated key, returning the anchor to verify the
            # credential with. `anchor_did` here is the root, not the issuer - a
            # rotated org's issuer DID is not known to the relying party in advance,
            # which is the whole point of pinning the root.
            history = ac.KeyHistory.from_json(c["key_history_json"])
            vc = ac.CapabilityCredential.from_json(c["credential_json"])

            def _rotated(history=history, vc=vc, root=c["anchor_did"]):
                vc.verify(history.authorize_issuer(root, vc.issuer))

            _check(c["name"], c["expect"], _rotated)

        elif kind == "approval_key":
            # Hybrid R10. The directory is the ONLY thing binding a key to a human, so
            # verifying the signature without consulting it would pass the accept case
            # and fail every reject case.
            directory = ac.ApproverDirectory.from_json(c["directory_json"])
            ev = ac.ApprovalEvidence.from_json(c["evidence_json"])
            action = ac.Action(c["action"]["tool"], c["action"]["parameters"])
            _check(c["name"], c["expect"],
                   lambda: ev.verify_with_directory(action, directory, anchor, _NOW))

        elif kind == "trust_config":
            # R2 through a trust framework: verify the config under the FRAMEWORK anchor,
            # then resolve the credential's issuer through it. `anchor_did` is the
            # framework here, not the credential's issuer.
            vc = ac.CapabilityCredential.from_json(c["credential_json"])

            def _framework(c=c, vc=vc, anchor=anchor):
                config = ac.SignedTrustConfig.from_json(c["config_json"])
                config.verify_current(anchor)
                registry = ac.TrustRegistry.from_config(config, anchor)
                entry = registry.verify_credential(vc)
                vc.verify(ac.TrustAnchor.from_did_key(entry.did))

            _check(c["name"], c["expect"], _framework)

        elif kind == "revocation":
            lst = ac.RevocationList.from_json(c["list_json"])
            lst.verify(anchor)  # must be authentic (raises otherwise)
            assert lst.is_revoked(c["revoked_index"]) is True, \
                f"{c['name']}: index {c['revoked_index']} should read as revoked"
            assert lst.is_revoked(c["clear_index"]) is False, \
                f"{c['name']}: index {c['clear_index']} should read as not revoked"

        else:
            raise ValueError(f"unknown vector kind: {kind}")

        print(f"  ok  {c['name']} ({kind})")

    print(f"conformance: {len(suite['cases'])} cases passed")


if __name__ == "__main__":
    try:
        test_conformance()
    except AssertionError as e:
        print(f"FAIL: {e}", file=sys.stderr)
        sys.exit(1)
