/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'agentcreds.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./agentcreds.android-arm64.node')
          } else {
            nativeBinding = require('@agentcreds/sdk-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'agentcreds.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./agentcreds.android-arm-eabi.node')
          } else {
            nativeBinding = require('@agentcreds/sdk-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'agentcreds.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./agentcreds.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@agentcreds/sdk-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'agentcreds.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./agentcreds.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@agentcreds/sdk-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'agentcreds.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./agentcreds.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@agentcreds/sdk-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'agentcreds.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./agentcreds.darwin-universal.node')
      } else {
        nativeBinding = require('@agentcreds/sdk-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'agentcreds.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./agentcreds.darwin-x64.node')
          } else {
            nativeBinding = require('@agentcreds/sdk-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'agentcreds.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./agentcreds.darwin-arm64.node')
          } else {
            nativeBinding = require('@agentcreds/sdk-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'agentcreds.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./agentcreds.freebsd-x64.node')
      } else {
        nativeBinding = require('@agentcreds/sdk-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'agentcreds.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./agentcreds.linux-x64-musl.node')
            } else {
              nativeBinding = require('@agentcreds/sdk-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'agentcreds.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./agentcreds.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@agentcreds/sdk-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'agentcreds.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./agentcreds.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@agentcreds/sdk-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'agentcreds.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./agentcreds.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@agentcreds/sdk-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'agentcreds.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./agentcreds.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@agentcreds/sdk-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'agentcreds.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./agentcreds.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@agentcreds/sdk-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'agentcreds.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./agentcreds.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@agentcreds/sdk-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'agentcreds.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./agentcreds.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@agentcreds/sdk-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'agentcreds.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./agentcreds.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@agentcreds/sdk-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { AuthzDecision, AdrStream, AdrCheckpoint, ApproverEntry, ApproverDirectory, ApprovalEvidence, AuditLog, AuditCompositor, EvidenceReport, EvidenceBundle, IdentityConfig, DelegationConfig, TrustConfig, AgentCredsConfig, CapabilityClaims, CredentialStatus, LinkedDataProof, CapabilityCredential, OwnershipRecord, Scope, Action, ChainEntry, DelegationChain, DelegationToken, PublicKey, VerificationMethod, DidDocument, AgentIdentity, TrustAnchor, InMemoryResolver, VerifiedHumanPrincipal, OidcProvider, issueOnBehalfOf, PopChallenge, ProofOfPossession, Presentation, HumanIdentity, TrustEntry, TrustRegistry, SignedTrustConfig, defaultListSize, RevocationList, RevocationRegistry, RotationStatement, KeyHistory, SdJwt, DisclosedCredential, SpiffeId, ValidatedSvid, SpiffeTrustBundle, issueFromSvid, MockOrg, MockAgent, FederationBridge, FederatedIdentity, version } = nativeBinding

module.exports.AuthzDecision = AuthzDecision
module.exports.AdrStream = AdrStream
module.exports.AdrCheckpoint = AdrCheckpoint
module.exports.ApproverEntry = ApproverEntry
module.exports.ApproverDirectory = ApproverDirectory
module.exports.ApprovalEvidence = ApprovalEvidence
module.exports.AuditLog = AuditLog
module.exports.AuditCompositor = AuditCompositor
module.exports.EvidenceReport = EvidenceReport
module.exports.EvidenceBundle = EvidenceBundle
module.exports.IdentityConfig = IdentityConfig
module.exports.DelegationConfig = DelegationConfig
module.exports.TrustConfig = TrustConfig
module.exports.AgentCredsConfig = AgentCredsConfig
module.exports.CapabilityClaims = CapabilityClaims
module.exports.CredentialStatus = CredentialStatus
module.exports.LinkedDataProof = LinkedDataProof
module.exports.CapabilityCredential = CapabilityCredential
module.exports.OwnershipRecord = OwnershipRecord
module.exports.Scope = Scope
module.exports.Action = Action
module.exports.ChainEntry = ChainEntry
module.exports.DelegationChain = DelegationChain
module.exports.DelegationToken = DelegationToken
module.exports.PublicKey = PublicKey
module.exports.VerificationMethod = VerificationMethod
module.exports.DidDocument = DidDocument
module.exports.AgentIdentity = AgentIdentity
module.exports.TrustAnchor = TrustAnchor
module.exports.InMemoryResolver = InMemoryResolver
module.exports.VerifiedHumanPrincipal = VerifiedHumanPrincipal
module.exports.OidcProvider = OidcProvider
module.exports.issueOnBehalfOf = issueOnBehalfOf
module.exports.PopChallenge = PopChallenge
module.exports.ProofOfPossession = ProofOfPossession
module.exports.Presentation = Presentation
module.exports.HumanIdentity = HumanIdentity
module.exports.TrustEntry = TrustEntry
module.exports.TrustRegistry = TrustRegistry
module.exports.SignedTrustConfig = SignedTrustConfig
module.exports.defaultListSize = defaultListSize
module.exports.RevocationList = RevocationList
module.exports.RevocationRegistry = RevocationRegistry
module.exports.RotationStatement = RotationStatement
module.exports.KeyHistory = KeyHistory
module.exports.SdJwt = SdJwt
module.exports.DisclosedCredential = DisclosedCredential
module.exports.SpiffeId = SpiffeId
module.exports.ValidatedSvid = ValidatedSvid
module.exports.SpiffeTrustBundle = SpiffeTrustBundle
module.exports.issueFromSvid = issueFromSvid
module.exports.MockOrg = MockOrg
module.exports.MockAgent = MockAgent
module.exports.FederationBridge = FederationBridge
module.exports.FederatedIdentity = FederatedIdentity
module.exports.version = version
