//! The delegation token format must not change without someone deciding that it should.
//!
//! `tests/fixtures/wire_compat.json` holds a real 2-hop token, checked in verbatim. If it
//! stops verifying, the token wire format moved - which means every token any issuer has
//! already handed out would stop verifying too. That failure is the point of the test.
//!
//! It deliberately exercises what is most likely to move: a TWO-HOP chain (authority
//! block plus a THIRD-PARTY attenuation block), an on-behalf-of principal binding, a
//! resource allow-list, and an R10 approval gate.
//!
//! ## Why two hops, specifically
//!
//! This file exists because of a mistake worth recording. The biscuit-auth 4 -> 6
//! migration was scoped on a probe that round-tripped a token built with
//! `append_with_keypair`, which reported wire-compatible. agentcreds-core does not use
//! that call - it attenuates with THIRD-PARTY blocks (`third_party_request` /
//! `create_block` / `append_third_party`), and biscuit-auth 6 versions those blocks
//! separately and rejects the v4 form outright ("Unsupported third party block
//! version"). A probe of a path the product does not take said "compatible" while real
//! product bytes did not survive.
//!
//! So the fixture is generated by the product's OWN mint/attenuate path, not by a
//! hand-built equivalent, and it is multi-hop. A single-hop fixture would have missed
//! exactly this.
//!
//! ## Why the data lives in a separate file
//!
//! The fixture is long hex, which secret scanners flag on entropy alone - it decodes to
//! `did:key` strings, which are public keys, but high-entropy ones. Keeping the data in
//! its own generator-produced JSON means that ONE path can be exempted from scanning
//! while this source file - which humans edit - stays fully scanned. Do not inline the
//! constants back into this file.
//!
//! ## Provenance
//!
//! Generated under biscuit-auth 6 at the migration cutover. Tokens minted under
//! biscuit-auth 4 with one or more delegation hops do NOT verify against this build;
//! depth-0 (unattenuated) tokens do. That break was taken deliberately while no issued
//! token depended on the format.
//!
//! Regenerate with `cargo run -p agentcreds-core --example gen_fixture` ONLY when a
//! format change is intended, and update this header with the reason.

use agentcreds_core::delegation::{Action, DelegationToken};
use agentcreds_core::did::TrustAnchor;
use agentcreds_core::vc::CapabilityCredential;

const FIXTURE_JSON: &str = include_str!("fixtures/wire_compat.json");

struct Fixture {
    token: DelegationToken,
    vc: CapabilityCredential,
    anchor: TrustAnchor,
    principal_did: String,
    /// The instant the fixture was generated. Tokens are capped at one hour by the
    /// autonomy ladder, so a decade-long fixture token is no longer expressible and this
    /// file would otherwise stop verifying an hour after regeneration. Judging as of this
    /// instant keeps the wire-format check about the WIRE FORMAT rather than the clock.
    evaluated_at: chrono::DateTime<chrono::Utc>,
}

fn fixture() -> Fixture {
    let doc: serde_json::Value =
        serde_json::from_str(FIXTURE_JSON).expect("fixture json must parse");
    let hex_field = |k: &str| {
        let s = doc[k]
            .as_str()
            .unwrap_or_else(|| panic!("fixture field {k} missing"));
        hex::decode(s).unwrap_or_else(|_| panic!("fixture field {k} must be hex"))
    };

    let vc_json = String::from_utf8(hex_field("vc_json_hex")).expect("fixture vc utf8");
    Fixture {
        token: DelegationToken::from_cbor(&hex_field("token_cbor_hex"))
            .expect("fixture token must decode"),
        vc: CapabilityCredential::from_json(&vc_json).expect("fixture credential must decode"),
        // Verify-only anchor rebuilt from its DID - no private key, which is why this
        // fixture is safe to commit at all.
        anchor: TrustAnchor::from_did_key(doc["anchor_did"].as_str().expect("anchor_did"))
            .expect("anchor did"),
        principal_did: doc["principal_did"]
            .as_str()
            .expect("principal_did")
            .to_string(),
        evaluated_at: chrono::DateTime::from_timestamp(
            doc["evaluated_at"]
                .as_i64()
                .expect("fixture missing `evaluated_at` - regenerate with examples/gen_fixture"),
            0,
        )
        .expect("fixture evaluated_at in range"),
    }
}

#[test]
fn checked_in_token_still_verifies() {
    let f = fixture();
    let action = Action::new("tool:echo", "text=hi")
        .on_resource("mailbox:alice@example.com/inbox")
        .on_behalf_of(&f.principal_did);
    f.token
        .verify_rooted_at(&action, &f.vc, &f.anchor, f.evaluated_at)
        .expect("the token wire format changed - see this file's header");
}

#[test]
fn checked_in_token_kept_its_shape() {
    let f = fixture();
    // Depth 1 proves the THIRD-PARTY attenuation block survived decoding, not just the
    // authority block - the exact distinction the migration probe got wrong.
    assert_eq!(f.token.depth(), 1, "2-hop chain: root + one attenuation");
    assert_eq!(
        f.token.principal_did(),
        Some(f.principal_did.as_str()),
        "the on-behalf-of binding must survive"
    );
    assert!(
        !f.token.gates().is_empty(),
        "the R10 approval gate must survive"
    );
}

#[test]
fn checked_in_token_still_enforces_its_limits() {
    // The negative direction matters as much: a decode that silently dropped the
    // parent's checks would still "verify", for things the chain never granted.
    let f = fixture();

    let wrong_tool = Action::new("tool:transfer", "amount=1")
        .on_resource("mailbox:alice@example.com/inbox")
        .on_behalf_of(&f.principal_did);
    assert!(
        f.token
            .verify_rooted(&wrong_tool, &f.vc, &f.anchor)
            .is_err(),
        "a tool outside the chain's scope must still be denied"
    );

    let wrong_resource = Action::new("tool:echo", "text=hi")
        .on_resource("mailbox:bob@example.com/inbox")
        .on_behalf_of(&f.principal_did);
    assert!(
        f.token
            .verify_rooted(&wrong_resource, &f.vc, &f.anchor)
            .is_err(),
        "a resource outside the allow-list must still be denied"
    );

    let swapped = Action::new("tool:echo", "text=hi")
        .on_resource("mailbox:alice@example.com/inbox")
        .on_behalf_of("did:key:zSomeoneElse");
    assert!(
        f.token.verify_rooted(&swapped, &f.vc, &f.anchor).is_err(),
        "the principal binding must still be enforced"
    );
}
